modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="zweihanderrp"
version="0.0.1"
displayName="zweihanderRP"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BoNDeX, FGR_UNN, Cerbin"
description='''
FOR ERIKUNI BECOUSE MCREATOR IS SHIT!!
'''

[[dependencies.zweihanderrp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"



[[dependencies.zweihanderrp]]
    modId="gecholib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

