modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="zweihanderrp"
version="0.0.1"
displayName="zweihanderRP"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="BoNDeX, FGR_UNN, Cerbin"
description="FOR ERIKUNI BECOUSE MCREATOR IS SHIT!!"

[[dependencies.zweihanderrp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.zweihanderrp]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

