modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="zweihander_test"
version="0.0.1"
displayName="zweihander_test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="BoNDeX, FGR_UNN"
description='''
FOR ERIKUNI BECOUSE MCREATOR IS SHIT!!
'''

[[dependencies.zweihander_test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




